### PR TITLE
I fix some windows error for ACR122U.

### PR DESCRIPTION
**Pull request by hotamy**
Now new pcsclite support windows.
I use ACR122U have error in windows8.1 .
[Error pic](https://raw.githubusercontent.com/hotamy/node-mifare-pcsc/master/pic/read_error.png)
I try fix.

### CODE REVIEW

**Comment by jbgosselin** [comment]
Wow i did this like 2 years ago, never thought somebody will use it

**Comment by jbgosselin** [comment]
Re-indenting all my file for changing one line is pretty bad

**Comment by jbgosselin** [comment]
I don't have card reader anymore, can you try on branch [develop](https://github.com/gossel-j/node-mifare-pcsc/tree/develop) ?

**Comment by jbgosselin** [comment]
If branch develop is working I'll create a new version and push to npm

**Comment by jbgosselin** [comment]
I updated it to use es6, you should do npm install and gulp to build the module before testing

**Comment by jbgosselin** [comment]
@hotamy just try to install it with the version 0.0.3-beta.0
`npm i mifare-pcsc@0.0.3-beta.0`
if it works tell me

**Comment by hotamy** [comment]
OK~ I will try.

**Comment by hotamy** [comment]
I run example
`git clone node-mifare-pcsc`
and 
`npm i mifare-pcsc@0.0.3-beta.0`

All get Error.
[Error Img](https://www.dropbox.com/s/6bfyvu38qqrmuk2/nfc-error.png?dl=0)

**Comment by jbgosselin** [comment]
@hotamy can you try this:

``` sh
rmdir node-mifare-pcsc
git clone node-mifare-pcsc
cd node-mifare-pcsc
npm install
node node_modules\.bin\gulp
node examples\nfc-uid-logger.js
```

**Comment by hotamy** [comment]
Error.
[step01](https://www.dropbox.com/s/1z5lu02xvb1d35g/nfc-step01.png?dl=0)
[step02](https://www.dropbox.com/s/xg6086hy1molfke/nfc-step02.png?dl=0)

**Comment by jbgosselin** [comment]
@hotamy you didn't run gulp properly
`node node_modules\.bin\gulp`
don't forget the '.' before bin

**Comment by jbgosselin** [comment]
Normally it should not work if you didn't run gulp, strange

**Comment by hotamy** [comment]
`node node_modules\.bin\gulp`
[error](https://www.dropbox.com/s/5t99vhq3k3hjkq1/gulb-error.png?dl=0)

**Comment by jbgosselin** [comment]
@hotamy your directory looks strange, can you check the package.json ?

**Comment by hotamy** [comment]
Strange...
`rmdir node-mifare-pcsc`
have problem...
alert "The specified path, file name, or both are too long." 

> D:\node-mifare-pcsc\node_modules\gulp\node_modules\gulp-util\node_modules\gulplog\node_modules\glogg\node_modules\sparkles

D:\node-mifare-pcsc>type package.json
{
  "name": "mifare-pcsc",
  "version": "0.0.3-beta.0",
  "description": "Use mifare 1K card",
  "main": "lib/index.js",
  "scripts": {
    "prepublish" : "gulp prepublish"
  },
  "dependencies": {
    "pcsclite": "0.4.8"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/gossel-j/node-mifare-pcsc.git"
  },
  "keywords": [
    "mifare",
    "pcsc",
    "pcsclite",
    "nfc",
    "rfid"
  ],
  "author": "dennajort",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/gossel-j/node-mifare-pcsc/issues"
  },
  "homepage": "https://github.com/gossel-j/node-mifare-pcsc",
  "devDependencies": {
    "babel-core": "^6.4.5",
    "babel-preset-es2015": "^6.3.13",
    "eslint": "^1.10.3",
    "gulp": "^3.9.0",
    "gulp-babel": "^6.1.2"
  }

## }

D:\node-mifare-pcsc\node_modules\gulp\package.json
{
  "name": "gulp",
  "description": "The streaming build system",
  "version": "3.9.0",
  "homepage": "http://gulpjs.com",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/gulpjs/gulp.git"
  },
  "author": {
    "name": "Fractal",
    "email": "contact@wearefractal.com",
    "url": "http://wearefractal.com/"
  },
  "tags": [
    "build",
    "stream",
    "system",
    "make",
    "tool",
    "asset",
    "pipeline"
  ],
  "files": [
    "index.js",
    "lib",
    "bin",
    "completion"
  ],
  "bin": {
    "gulp": "./bin/gulp.js"
  },
  "man": [
    "gulp.1"
  ],
  "dependencies": {
    "archy": "^1.0.0",
    "chalk": "^1.0.0",
    "deprecated": "^0.0.1",
    "gulp-util": "^3.0.0",
    "interpret": "^0.6.2",
    "liftoff": "^2.1.0",
    "minimist": "^1.1.0",
    "orchestrator": "^0.3.0",
    "pretty-hrtime": "^1.0.0",
    "semver": "^4.1.0",
    "tildify": "^1.0.0",
    "v8flags": "^2.0.2",
    "vinyl-fs": "^0.3.0"
  },
  "devDependencies": {
    "coveralls": "^2.7.0",
    "graceful-fs": "^3.0.0",
    "istanbul": "^0.3.0",
    "jscs": "~1.12.0",
    "jshint": "^2.5.0",
    "jshint-stylish": "^1.0.0",
    "marked-man": "^0.1.3",
    "mkdirp": "^0.5.0",
    "mocha": "^2.0.1",
    "mocha-lcov-reporter": "^0.0.1",
    "q": "^1.0.0",
    "rimraf": "^2.2.5",
    "should": "^5.0.1"
  },
  "scripts": {
    "prepublish": "marked-man --name gulp docs/CLI.md > gulp.1",
    "lint": "jshint lib bin test index.js --reporter node_modules/jshint-stylish/stylish.js --exclude node_modules && jscs lib bin test index.js",
    "test": "npm run-script lint && mocha --reporter spec",
    "coveralls": "istanbul cover _mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | coveralls && rm -rf ./coverage"
  },
  "engines": {
    "node": ">= 0.9"
  },
  "license": "MIT",
  "gitHead": "657213a52d5e9c19b85df6a42f76341a98c08ae8",
  "bugs": {
    "url": "https://github.com/gulpjs/gulp/issues"
  },
  "_id": "gulp@3.9.0",
  "_shasum": "cf1fba4cb558bb8c6ae6c9613f583ae2620d214a",
  "_from": "gulp@>=3.9.0 <4.0.0",
  "_npmVersion": "2.8.3",
  "_nodeVersion": "0.10.36",
  "_npmUser": {
    "name": "phated",
    "email": "blaine@iceddev.com"
  },
  "maintainers": [
    {
      "name": "fractal",
      "email": "contact@wearefractal.com"
    },
    {
      "name": "phated",
      "email": "blaine@iceddev.com"
    }
  ],
  "dist": {
    "shasum": "cf1fba4cb558bb8c6ae6c9613f583ae2620d214a",
    "tarball": "http://registry.npmjs.org/gulp/-/gulp-3.9.0.tgz"
  },
  "directories": {},
  "_resolved": "https://registry.npmjs.org/gulp/-/gulp-3.9.0.tgz",
  "readme": "ERROR: No README data found!"
}

**Comment by jbgosselin** [comment]
@hotamy ok i just pushed a new beta version.

In an empty directory just do `npm i mifare-pcsc@0.0.3-beta.1` and copy my example file, replace the require with `require("mifare-pcsc")` and lets see if it works

**Comment by jbgosselin** [comment]
@hotamy And to be honest I'm not used at all about developing on Windows :pensive:, soon I should have a new card reader and I can try fix it better with my Windows at home.

**Comment by jbgosselin** [comment]
@hotamy And I'm thinking about doing some breaking changes. Maybe use promises, maybe use events, maybe other things

**Comment by hotamy** [comment]
Thanks~

**Comment by jbgosselin** [comment]
@hotamy it works ?
I will receive my reader today I will try tomorrow.

**Comment by jbgosselin** [comment]
Ok I updated to version 0.0.3

**Pull request closed without merging**
